#ifndef MATRIX_H
#define MATRIX_H

#include "stm32l4xx"
#include "stm32l475xx"

#define GPOIA_MODER_Msk GPIO_MODER_MODE2_Msk|GPIO_MODER_MODE3_Msk|GPIO_MODER_MODE4_Msk|GPIO_MODER_MODE5_Msk|GPIO_MODER_MODE6_Msk|GPIO_MODER_MODE7_Msk|GPIO_MODER_MODE15_Msk
#define GPOIA_MODER_0   GPIO_MODER_MODE2_0|GPIO_MODER_MODE3_0|GPIO_MODER_MODE4_0|GPIO_MODER_MODE5_0|GPIO_MODER_MODE6_0|GPIO_MODER_MODE7_0|GPIO_MODER_MODE15_0
#define GPIOB_MODER_Msk GPIO_MODER_MODE1_Msk|GPIO_MODER_MODE2_Msk|GPIO_MODER_MODE3_Msk
#define GPIOB_MODER_0   GPIO_MODER_MODE1_0|GPIO_MODER_MODE2_0|GPIO_MODER_MODE3_0
#define GPIOC_MODER_Msk GPIO_MODER_MODE3_Msk|GPIO_MODER_MODE4_Msk|GPIO_MODER_MODE5_Msk
#define GPIOC_MODER_0   GPIO_MODER_MODE3_0|GPIO_MODER_MODE4_0|GPIO_MODER_MODE5_0


#define ROW0(x)         WRITE_REG(GPIOB->BSRR, x?GPIO_BSRR_BS2:GPIO_BSRR_BR2)
#define ROW1(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS15:GPIO_BSRR_BR15)
#define ROW2(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS2:GPIO_BSRR_BR2)
#define ROW3(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS7:GPIO_BSRR_BR7)
#define ROW4(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS6:GPIO_BSRR_BR6)
#define ROW5(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS5:GPIO_BSRR_BR5)
#define ROW6(x)         WRITE_REG(GPIOB->BSRR, x?GPIO_BSRR_BS0:GPIO_BSRR_BR0)
#define ROW7(x)         WRITE_REG(GPIOA->BSRR, x?GPIO_BSRR_BS3:GPIO_BSRR_BR3)


void matrix_init(void);

#endif
